coverage:
  precision: 2
  round: down
  range: "50...70"
  status:
    project:
      default:
        target: auto
        # We allow a 2% drop from the previous base commit coverage
        threshold: 2%
    # Disable patch since it is noisy and not correct
    patch:
      default:
        enabled: no
        if_not_found: success