# Check if the URLs in README are valid.
# Use awesome_bot to do the check.

name: url

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  check-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Awesome Bot
        run: gem install awesome_bot
      - name: Check URLs
        run: awesome_bot README.md --allow-dupe --allow-redirect